services:
  techostrea:
    container_name: poc-technostrea
    image: technostrea/poc-technostrea:stabe-alpine
    expose:
      - 80
      - 443
    scale: 1
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.technostrea.rule=Host(`${DOMAINE_NAME_OR_STATIC_IP}`) || PathPrefix(`/technostrea`)' # Regle de routage
      - 'traefik.http.routers.technostrea.service=technostrea-svc'
      - 'traefik.http.services.technostrea-svc.loadbalancer.server.port=80'
      - 'traefik.http.routers.technostrea.entrypoints=web'
      - "traefik.http.middlewares.technostrea-middleware.stripprefix.prefixes=/technostrea"
      - 'traefik.http.routers.technostrea.middlewares=technostrea-middleware@docker'
