services:
  techostrea:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poc-technostrea
    platform: linux/arm64
    expose:
      - 80
      - 443
    scale: 1
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.technostrea.rule=Host(`${DOMAINE_NAME_OR_STATIC_IP}`) || PathPrefix(`/technostrea`)' # Regle de routage
      - 'traefik.http.routers.technostrea.service=technostrea-svc'
      - 'traefik.http.services.technostrea-svc.loadbalancer.server.port=80'
      - 'traefik.http.routers.technostrea.entrypoints=web'
      - "traefik.http.middlewares.technostrea-middleware.stripprefix.prefixes=/technostrea"
      - 'traefik.http.routers.technostrea.middlewares=technostrea-middleware@docker'
