name: Deploy to Raspberry Pi DEV

on:
  push:
    branches:
      - dev

  workflow_dispatch: # Déclenchement manuel

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: dev

    steps:
      # Checkout le code de la branche
      - name: Checkout repository
        uses: actions/checkout@v2

      # Copier l'image dans le serveur de dev
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          port: ${{ secrets.PI_SSH_PORT }}
          rm: true
          source: "*"
          target: /home/${{ secrets.PI_USER }}/Documents/poc-projects/poc-technostrea/


      # Decompresser l'image dans le serveur de dev
      - name: executing remote ssh commands using ssh-key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          port: ${{ secrets.PI_SSH_PORT }}
          script: |
              cd /home/${{ secrets.PI_USER }}/Documents/poc-projects/poc-technostrea/
              cp /home/${{ secrets.PI_USER }}/Documents/poc-projects/poc-traefik/poc-traefik/.env .env
              echo "# Building the docker image"
              docker build -t technostrea/poc-technostrea:stabe-alpine .
              echo "# Suppression du dossier"
              rm -rf /home/${{ secrets.PI_USER }}/Documents/poc-projects/poc-technostrea/*
